// Generates the design system's token layer out of
// src/design-system/tokens/tokens.json:
//
//   tokens.css  the custom properties, which is what the browser reads
//   index.ts    the same names as typed `var(--…)` strings, for TypeScript
//
//   npm run tokens        # regenerate both
//   npm run tokens:check  # verify the committed copies match the source (CI)
//
// Both outputs are committed, for the same reason the JSON Schemas are: a
// stylesheet cannot import JSON, and a component that wants a token in a style
// attribute needs it as a value it can autocomplete. The check mode regenerates
// into memory and compares, so a token added to the JSON without a regeneration
// fails in CI instead of shipping a CSS file that is missing it — the exact way
// `--surface-alt` came to be used in six rules while being defined in none.
//
// The generator is deliberately dumb: no colour maths, no aliasing pass, no
// theme merging. A token's value is what the JSON says, and `var(--x)` in a
// value is passed through untouched so one token can be defined in terms of
// another (`--overdue: var(--danger)`). Anything cleverer belongs in the
// stylesheet that consumes it.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SOURCE = 'src/design-system/tokens/tokens.json';
const CSS_OUT = 'src/design-system/tokens/tokens.css';
const TS_OUT = 'src/design-system/tokens/index.ts';

const check = process.argv.includes('--check');

type Group = Record<string, string> & { $prefix?: string; $comment?: string };
type Source = Record<string, Group | string>;

const source = JSON.parse(readFileSync(resolve(REPO_ROOT, SOURCE), 'utf8')) as Source;

/** Groups only — `$comment` at the top level documents the file itself. */
const groups = Object.entries(source).filter(
  (entry): entry is [string, Group] => !entry[0].startsWith('$') && typeof entry[1] === 'object',
);

/** `--<prefix><key>`, the name the browser and the TypeScript accessor both use. */
function cssName(group: Group, key: string): string {
  return `--${group.$prefix ?? ''}${key}`;
}

function entriesOf(group: Group): [string, string][] {
  return Object.entries(group).filter(([key]) => !key.startsWith('$'));
}

/**
 * A TypeScript identifier for a token key, since the scale steps are not
 * identifiers (`2xs`, `0-border`). Quoting every key would be uniform but
 * `tokens.space['2xs']` reads worse than `tokens.space.xs2` everywhere it is
 * used, so a leading digit moves to the back and dashes camel-case.
 */
function tsKey(key: string): string {
  const camel = key.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
  if (!/^\d/.test(camel)) return camel;
  // `2xs` → `xs2`, `0-border` → `border0`. The tail is lower-cased again because
  // moving the digit promotes what was a camel-case hump to the front.
  return camel.replace(
    /^(\d+)(.*)$/,
    (_, digits: string, rest: string) => `${rest ? rest[0].toLowerCase() + rest.slice(1) : 'n'}${digits}`,
  );
}

function banner(what: string): string {
  return `Generated by scripts/design-system/build-tokens.ts from ${SOURCE}.\nDo not edit: run \`npm run tokens\` instead. CI fails when this file and the\nsource disagree (\`npm run tokens:check\`).\n\n${what}`;
}

function buildCss(): string {
  const out: string[] = [`/* ${banner('The custom properties every stylesheet and component reads.').replace(/\n/g, '\n   ')} */\n`];
  out.push(':root {');
  groups.forEach(([name, group], index) => {
    if (index > 0) out.push('');
    if (group.$comment) {
      out.push(`  /* ${name}: ${wrap(group.$comment, 76, '     ')} */`);
    } else {
      out.push(`  /* ${name} */`);
    }
    for (const [key, value] of entriesOf(group)) {
      out.push(`  ${cssName(group, key)}: ${value};`);
    }
  });
  out.push('}');
  return out.join('\n') + '\n';
}

function buildTs(): string {
  const out: string[] = [`// ${banner('The same names as `var(--…)` strings, for the rare component that needs a\ntoken in a style attribute rather than in its stylesheet.').replace(/\n/g, '\n// ')}\n`];
  out.push('export const tokens = {');
  groups.forEach(([name, group], index) => {
    if (index > 0) out.push('');
    if (group.$comment) out.push(`  /** ${wrap(group.$comment, 74, '   * ')} */`);
    out.push(`  ${name}: {`);
    for (const [key, value] of entriesOf(group)) {
      out.push(`    /** \`${value}\` */`);
      out.push(`    ${tsKey(key)}: 'var(${cssName(group, key)})',`);
    }
    out.push('  },');
  });
  out.push('} as const;');
  out.push('');
  out.push('/** Every custom property the token layer defines, for the contract check. */');
  out.push('export const TOKEN_NAMES: readonly string[] = [');
  for (const [, group] of groups) {
    for (const [key] of entriesOf(group)) out.push(`  '${cssName(group, key)}',`);
  }
  out.push('];');
  return out.join('\n') + '\n';
}

/** Reflow a comment so a long `$comment` does not produce a 400-column line. */
function wrap(text: string, width: number, indent: string): string {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = '';
  for (const word of words) {
    if (line && line.length + word.length + 1 > width) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);
  return lines.join(`\n${indent}`);
}

let failed = false;

/** A blank line inside a `//`- or ` * `-prefixed comment block otherwise keeps
 *  the prefix's trailing space, which every editor and linter strips back out. */
const trimTrailing = (text: string): string => text.replace(/[ \t]+$/gm, '');

for (const [out, generated] of [
  [CSS_OUT, trimTrailing(buildCss())],
  [TS_OUT, trimTrailing(buildTs())],
] as const) {
  const path = resolve(REPO_ROOT, out);
  if (check) {
    let committed: string;
    try {
      committed = readFileSync(path, 'utf8');
    } catch {
      failed = true;
      console.error(`[tokens] MISSING ${out} — run 'npm run tokens'.`);
      continue;
    }
    if (committed === generated) {
      console.log(`[tokens] ok    ${out} matches ${SOURCE}`);
    } else {
      failed = true;
      console.error(`[tokens] STALE ${out} no longer matches ${SOURCE} — run 'npm run tokens'.`);
    }
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, generated);
    console.log(`[tokens] wrote ${out} from ${SOURCE}`);
  }
}

if (failed) process.exit(1);
