// Generated by scripts/design-system/build-tokens.ts from src/design-system/tokens/tokens.json.
// Do not edit: run `npm run tokens` instead. CI fails when this file and the
// source disagree (`npm run tokens:check`).
//
// The same names as `var(--…)` strings, for the rare component that needs a
// token in a style attribute rather than in its stylesheet.

export const tokens = {
  /** The neutral built-in theme. Overriding any of these in a stylesheet loaded
   * after tokens.css is the supported way to recolour the viewer. */
  color: {
    /** `#fbfbfb` */
    bg: 'var(--bg)',
    /** `#ffffff` */
    surface: 'var(--surface)',
    /** `rgba(47, 13, 91, 0.06)` */
    surfaceAlt: 'var(--surface-alt)',
    /** `#2c3333` */
    fg: 'var(--fg)',
    /** `#2f0d5b99` */
    fgMuted: 'var(--fg-muted)',
    /** `rgba(47, 13, 91, 0.15)` */
    border: 'var(--border)',
    /** `rgba(47, 13, 91, 0.06)` */
    hover: 'var(--hover)',
    /** `#2f0d5b` */
    accent: 'var(--accent)',
    /** `#c1b6ce` */
    accentSoft: 'var(--accent-soft)',
    /** `#2f0d5b` */
    accentStrong: 'var(--accent-strong)',
    /** `#ffa800` */
    warning: 'var(--warning)',
    /** `#d3333a` */
    danger: 'var(--danger)',
    /** `#f5e3cf` */
    highlight: 'var(--highlight)',
    /** `#94d825` */
    success: 'var(--success)',
    /** `#f32ed4` */
    magenta: 'var(--magenta)',
  },

  /** Item status (Open/Doing/Done, see src/status.ts). The status dot maps a
   * value to one of these and nothing else does, so a fourth status needs a
   * colour here and a case there. */
  status: {
    /** `#94a3b8` */
    open: 'var(--status-open)',
    /** `#315dff` */
    doing: 'var(--status-doing)',
    /** `#1d9e75` */
    done: 'var(--status-done)',
  },

  /** The timeline bar itself. */
  item: {
    /** `#ffffff` */
    bg: 'var(--item-bg)',
    /** `#2f0d5b` */
    fg: 'var(--item-fg)',
    /** `#2f0d5b` */
    border: 'var(--item-border)',
    /** `#f5e3cf` */
    bgActive: 'var(--item-bg-active)',
  },

  /** vis-timeline's own furniture: the grid behind the bars and the date axis. */
  chart: {
    /** `rgba(47, 13, 91, 0.08)` */
    gridLine: 'var(--grid-line)',
    /** `rgba(47, 13, 91, 0.18)` */
    gridLineMajor: 'var(--grid-line-major)',
    /** `#2f0d5b` */
    axisText: 'var(--axis-text)',
    /** `var(--danger)` */
    overdue: 'var(--overdue)',
  },

  /** Six group colours, cycled. A border and its matching fill are one pair:
   * buildItems.ts picks the index, and both halves have to move together or a
   * bar gets one group's outline around another's fill. */
  lane: {
    /** `#2f0d5b` */
    border0: 'var(--lane-0-border)',
    /** `#e5dcef` */
    bg0: 'var(--lane-0-bg)',
    /** `#ffa800` */
    border1: 'var(--lane-1-border)',
    /** `#ffe7be` */
    bg1: 'var(--lane-1-bg)',
    /** `#f32ed4` */
    border2: 'var(--lane-2-border)',
    /** `#fcc8f4` */
    bg2: 'var(--lane-2-bg)',
    /** `#94d825` */
    border3: 'var(--lane-3-border)',
    /** `#e1f0bd` */
    bg3: 'var(--lane-3-bg)',
    /** `#e8ac68` */
    border4: 'var(--lane-4-border)',
    /** `#f5e3cf` */
    bg4: 'var(--lane-4-bg)',
    /** `#c1b6ce` */
    border5: 'var(--lane-5-border)',
    /** `#efeaf3` */
    bg5: 'var(--lane-5-bg)',
  },

  /** The spacing scale. Padding, margin and gap take a step from here; a raw px
   * value in one of those three properties is what check-design-system.sh
   * rejects. Geometry that is not spacing (an icon's width, a border) is a
   * size token or a literal, not a step on this scale. */
  space: {
    /** `2px` */
    xs3: 'var(--space-3xs)',
    /** `4px` */
    xs2: 'var(--space-2xs)',
    /** `6px` */
    xs: 'var(--space-xs)',
    /** `8px` */
    sm: 'var(--space-sm)',
    /** `12px` */
    md: 'var(--space-md)',
    /** `16px` */
    lg: 'var(--space-lg)',
    /** `20px` */
    xl: 'var(--space-xl)',
    /** `24px` */
    xl2: 'var(--space-2xl)',
    /** `32px` */
    xl3: 'var(--space-3xl)',
  },

  /** `xs` is for a row nested inside an `sm` surface — a menu item in a menu.
   * Matching the parent's radius there makes the row look like it is bleeding
   * past the corner. */
  radius: {
    /** `4px` */
    xs: 'var(--radius-xs)',
    /** `6px` */
    sm: 'var(--radius-sm)',
    /** `8px` */
    md: 'var(--radius-md)',
    /** `9999px` */
    pill: 'var(--radius-pill)',
  },

  /** The shape of a round mark: avatars, status dots, point items. Set to a
   * small length to square the whole viewer's marks off in one move. */
  mark: {
    /** `50%` */
    markRadius: 'var(--mark-radius)',
  },

  /** Font sizes. `md` (13px) is the form and control size, `base` (14px) is
   * body copy — controls sit a step below their surroundings throughout. */
  text: {
    /** `10px` */
    xs2: 'var(--text-2xs)',
    /** `11px` */
    xs: 'var(--text-xs)',
    /** `12px` */
    sm: 'var(--text-sm)',
    /** `13px` */
    md: 'var(--text-md)',
    /** `14px` */
    base: 'var(--text-base)',
    /** `18px` */
    lg: 'var(--text-lg)',
    /** `22px` */
    xl: 'var(--text-xl)',
  },

  weight: {
    /** `400` */
    normal: 'var(--weight-normal)',
    /** `500` */
    medium: 'var(--weight-medium)',
    /** `600` */
    semibold: 'var(--weight-semibold)',
    /** `700` */
    bold: 'var(--weight-bold)',
  },

  leading: {
    /** `1.25` */
    tight: 'var(--leading-tight)',
    /** `1.4` */
    snug: 'var(--leading-snug)',
    /** `1.5` */
    normal: 'var(--leading-normal)',
    /** `1.6` */
    relaxed: 'var(--leading-relaxed)',
  },

  font: {
    /** `system-ui, -apple-system, sans-serif` */
    body: 'var(--font-body)',
    /** `Georgia, serif` */
    headline: 'var(--font-headline)',
    /** `ui-monospace, SFMono-Regular, Menlo, monospace` */
    mono: 'var(--font-mono)',
  },

  headline: {
    /** `500` */
    headlineWeight: 'var(--headline-weight)',
  },

  /** Interactive-element heights. `md` is the picker trigger, `lg` the close
   * button and the segmented control — they share a line in the detail panel's
   * header, so the two values are what keeps that row level. */
  control: {
    /** `28px` */
    sm: 'var(--control-sm)',
    /** `30px` */
    md: 'var(--control-md)',
    /** `32px` */
    lg: 'var(--control-lg)',
  },

  /** Named `icon-size-` rather than `icon-`: the glyph set in icons.css already
   * owns `--icon-<key>`, and a size token colliding with a mask URL fails
   * silently. */
  iconSize: {
    /** `8px` */
    xs: 'var(--icon-size-xs)',
    /** `10px` */
    sm: 'var(--icon-size-sm)',
    /** `16px` */
    md: 'var(--icon-size-md)',
    /** `18px` */
    lg: 'var(--icon-size-lg)',
  },

  /** One person, one monogram (see src/users.ts). `sm` sits on a text line
   * inside a chip or table cell, `md` stands alone in the header. */
  avatar: {
    /** `18px` */
    sm: 'var(--avatar-sm)',
    /** `28px` */
    md: 'var(--avatar-md)',
  },

  /** One elevation per kind of thing that leaves the surface: anything anchored
   * to a trigger, the side panel, the sticky header's scroll shadow, a small
   * mark sitting on top of something else, and an item being dragged.
   * `popover` is shared by the menus, the pickers, the autosuggests and the
   * pricing view's own layers — those were three slightly different shadows
   * for one idea. */
  shadow: {
    /** `0 8px 24px rgba(0, 0, 0, 0.12)` */
    popover: 'var(--shadow-popover)',
    /** `-12px 0 28px -18px rgba(0, 0, 0, 0.35)` */
    panel: 'var(--shadow-panel)',
    /** `0 4px 8px -4px rgba(0, 0, 0, 0.12)` */
    header: 'var(--shadow-header)',
    /** `0 1px 2px rgba(0, 0, 0, 0.18)` */
    mark: 'var(--shadow-mark)',
    /** `0 1px 3px rgba(0, 0, 0, 0.12)` */
    bar: 'var(--shadow-bar)',
    /** `0 2px 4px rgba(0, 0, 0, 0.25)` */
    drag: 'var(--shadow-drag)',
  },

  /** The stacking order, in one place because it is a single ordering and used
   * to be eight numbers spread over five stylesheets. `arrows` is the
   * dependency overlay inside the chart; `skeleton` must beat vis-timeline's
   * own layers (which reach 10) or the loading placeholder is drawn through; a
   * context menu is the topmost thing on screen. */
  z: {
    /** `1` */
    base: 'var(--z-base)',
    /** `3` */
    sticky: 'var(--z-sticky)',
    /** `5` */
    arrows: 'var(--z-arrows)',
    /** `11` */
    skeleton: 'var(--z-skeleton)',
    /** `20` */
    panel: 'var(--z-panel)',
    /** `30` */
    popover: 'var(--z-popover)',
    /** `60` */
    pluginPopover: 'var(--z-plugin-popover)',
    /** `70` */
    menu: 'var(--z-menu)',
  },

  /** Hover and focus feedback is `fast`; anything that appears or moves on its
   * own is `slow`. Both are honoured only outside prefers-reduced-motion. */
  motion: {
    /** `0.1s ease` */
    fast: 'var(--motion-fast)',
    /** `0.2s ease` */
    slow: 'var(--motion-slow)',
  },

  /** One ring for the whole viewer. Editing surfaces are the documented
   * exception: an input tints its border instead, because a 2px ring around
   * every field you touch reads as a frame (see the Input component). */
  focus: {
    /** `2px solid var(--accent)` */
    ring: 'var(--focus-ring)',
    /** `2px` */
    ringOffset: 'var(--focus-ring-offset)',
  },
} as const;

/** Every custom property the token layer defines, for the contract check. */
export const TOKEN_NAMES: readonly string[] = [
  '--bg',
  '--surface',
  '--surface-alt',
  '--fg',
  '--fg-muted',
  '--border',
  '--hover',
  '--accent',
  '--accent-soft',
  '--accent-strong',
  '--warning',
  '--danger',
  '--highlight',
  '--success',
  '--magenta',
  '--status-open',
  '--status-doing',
  '--status-done',
  '--item-bg',
  '--item-fg',
  '--item-border',
  '--item-bg-active',
  '--grid-line',
  '--grid-line-major',
  '--axis-text',
  '--overdue',
  '--lane-0-border',
  '--lane-0-bg',
  '--lane-1-border',
  '--lane-1-bg',
  '--lane-2-border',
  '--lane-2-bg',
  '--lane-3-border',
  '--lane-3-bg',
  '--lane-4-border',
  '--lane-4-bg',
  '--lane-5-border',
  '--lane-5-bg',
  '--space-3xs',
  '--space-2xs',
  '--space-xs',
  '--space-sm',
  '--space-md',
  '--space-lg',
  '--space-xl',
  '--space-2xl',
  '--space-3xl',
  '--radius-xs',
  '--radius-sm',
  '--radius-md',
  '--radius-pill',
  '--mark-radius',
  '--text-2xs',
  '--text-xs',
  '--text-sm',
  '--text-md',
  '--text-base',
  '--text-lg',
  '--text-xl',
  '--weight-normal',
  '--weight-medium',
  '--weight-semibold',
  '--weight-bold',
  '--leading-tight',
  '--leading-snug',
  '--leading-normal',
  '--leading-relaxed',
  '--font-body',
  '--font-headline',
  '--font-mono',
  '--headline-weight',
  '--control-sm',
  '--control-md',
  '--control-lg',
  '--icon-size-xs',
  '--icon-size-sm',
  '--icon-size-md',
  '--icon-size-lg',
  '--avatar-sm',
  '--avatar-md',
  '--shadow-popover',
  '--shadow-panel',
  '--shadow-header',
  '--shadow-mark',
  '--shadow-bar',
  '--shadow-drag',
  '--z-base',
  '--z-sticky',
  '--z-arrows',
  '--z-skeleton',
  '--z-panel',
  '--z-popover',
  '--z-plugin-popover',
  '--z-menu',
  '--motion-fast',
  '--motion-slow',
  '--focus-ring',
  '--focus-ring-offset',
];
